version: '3.9'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql-db-data:/var/lib/mysql